2019-01-22 15:40:58,811 - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macaca/remote_invoker.py[line:139] - DEBUG: Method: POST, Url: http://localhost:3456/wd/hub/session/45563d12-7681-40ce-8b59-72757fe65867/element, Body: {'using': 'name', 'value': '6'}.
2019-01-22 15:40:58,815 - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py[line:208] - DEBUG: Starting new HTTP connection (1): localhost
